# Generated by Django 5.0.4 on 2024-05-02 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApInvoice',
            fields=[
                ('entry_type_id', models.CharField(blank=True, max_length=3, null=True)),
                ('pie_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('invoice_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ap_invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('debit_credit', models.CharField(max_length=6)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'ap_invoice_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApPayment',
            fields=[
                ('entry_type_id', models.CharField(blank=True, max_length=3, null=True)),
                ('ppe_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'ap_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('debit_credit', models.CharField(max_length=6)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'ap_payment_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=10)),
                ('zipcode_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('county_name', models.CharField(blank=True, max_length=40, null=True)),
                ('area', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'area_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArInvoice',
            fields=[
                ('entry_type_id', models.CharField(blank=True, max_length=3, null=True)),
                ('rie_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'ar_invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('debit_credit', models.CharField(blank=True, max_length=6, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'ar_invoice_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArReceipt',
            fields=[
                ('entry_type_id', models.CharField(blank=True, max_length=3, null=True)),
                ('rre_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'ar_receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('debit_credit', models.CharField(max_length=6)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'ar_receipt_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BsPlIdx',
            fields=[
                ('bs_pl_index', models.IntegerField(primary_key=True, serialize=False)),
                ('bs_pl_cat_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'bs_pl_idx',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('business_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_type_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'business_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_ledger_number', models.IntegerField(unique=True)),
                ('general_ledger_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'chart_of_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoaCategories',
            fields=[
                ('coacat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coa_category_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'coa_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostCentres',
            fields=[
                ('cc_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cost_centres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('functional_currency', models.BooleanField()),
            ],
            options={
                'db_table': 'currencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'customer_addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerNames',
            fields=[
                ('customer_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('business_type_id', models.IntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('general_ledger_number', models.IntegerField(blank=True, null=True)),
                ('currency_id', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeNames',
            fields=[
                ('employee_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('entry_type_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('entry_type_name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'entry_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('start_date', models.DateField(unique=True)),
                ('end_date', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'fiscal_months',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('grade_code', models.IntegerField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('je_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'journal_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('debit_credit', models.CharField(max_length=6)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'journal_entry_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('cat_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=20)),
                ('subcat_id', models.IntegerField(blank=True, null=True)),
                ('subcat_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'product_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=60)),
                ('product_unit_name', models.CharField(blank=True, max_length=30, null=True)),
                ('product_units', models.IntegerField(blank=True, null=True)),
                ('product_unit_price', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitCentres',
            fields=[
                ('pc_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('pc_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'profit_centres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('p_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_order_date', models.DateField()),
            ],
            options={
                'db_table': 'purchase_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrdersItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_ledger_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_orders_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoices',
            fields=[
                ('invoice_date', models.DateField()),
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'sales_invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrders',
            fields=[
                ('sales_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_order_date', models.DateField()),
            ],
            options={
                'db_table': 'sales_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrdersItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=6, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('unit_selling_price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('shipped', models.BooleanField()),
            ],
            options={
                'db_table': 'sales_orders_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCoaCategories',
            fields=[
                ('sub_coacat_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_coacat_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'sub_coa_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_code', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=4)),
                ('tax_area', models.CharField(max_length=20)),
                ('tax_belongto', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendorAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=250)),
                ('address_line2', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vendor_addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendor_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=60)),
                ('general_ledger_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wbs',
            fields=[
                ('wbs_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'wbs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeCostCentres',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='araging.employeenames')),
            ],
            options={
                'db_table': 'employee_cost_centres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaries',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='araging.employeenames')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'employee_salaries',
                'managed': False,
            },
        ),
    ]
